/* Generated by tools/gen_assets.py - do not edit. */
#ifndef GFX_H
#define GFX_H

#include <gbdk/platform.h>
#include <stdint.h>

#define GFX_NUM_TILES   134
#define GFX_MAX_EXP     16
#define GFX_CELL_TILES  4
#define GFX_UI_BASE     0

extern const uint8_t gfx_tiles[134 * 16];
extern const uint8_t gfx_cell_map[17][16];
extern const uint8_t gfx_palette_for_exp[17];
extern const palette_color_t gfx_bkg_palettes[8 * 4];

/* Map an ASCII character to its font tile index. */
uint8_t gfx_char_tile(char c);

#endif
